const PHOTOS = [
  'https://images.unsplash.com/photo-1618354691438-25bc04584c23?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1651761179569-4ba2aa054997?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1618677603286-0ec56cb6e1b5?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1716951884284-4d138f2c42b2?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1714070700742-b59b045d2dd9?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1622445270936-5dcb604970e7?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1773525912457-6a7278efb9e4?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1622445275649-b1922cc3e837?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1671438118097-479e63198629?w=400&h=500&fit=crop',
  'https://images.unsplash.com/photo-1618354691551-44de113f0164?w=400&h=500&fit=crop',
]

const COLLECTIONS = [
  { id: 'street-canvas', name: 'Street Canvas', desc: 'Urban art inspired. 24 designs.', icon: '✦', bg: '#1a1a2e', text: '#fff' },
  { id: 'earth-tone', name: 'Earth Tone', desc: 'Organic minimal. 18 designs.', icon: '○', bg: '#f5f0e1', text: '#111' },
  { id: 'retro-wave', name: 'Retro Wave', desc: 'Synth meets street. 15 designs.', icon: '◈', bg: '#0d0d0d', text: '#fff' },
  { id: 'bloom-society', name: 'Bloom Society', desc: 'Botanical reimagined. 12 designs.', icon: '◇', bg: '#f8f0f0', text: '#111' },
  { id: 'cyber-punk', name: 'Cyber Punk', desc: 'Future forward. 10 designs.', icon: '▣', bg: '#1e1e1e', text: '#fff' },
  { id: 'summer-daze', name: 'Summer Daze', desc: 'Vacation ready. 20 designs.', icon: '△', bg: '#faf5eb', text: '#111' },
]

const ALL_SIZES = ['XS', 'S', 'M', 'L', 'XL', '2XL']
const ALL_CATEGORIES = ['Graphic Tees', 'Oversized Fit', 'Premium Fit', 'Organic Cotton', 'Limited Edition']

const products = [
  { id: 1, name: 'Mountain Graphic Tee', category: 'Graphic Tees', price: 38, oldPrice: null, tag: 'Best seller', collection: 'street-canvas',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: [{ n: 'Black', h: '#111' }, { n: 'White', h: '#fff' }, { n: 'Gray', h: '#555' }], image: PHOTOS[0], featured: true, isNew: false, rating: 4.8, reviews: 124 },
  { id: 2, name: 'Relaxed Fit Pocket Tee', category: 'Oversized Fit', price: 42, oldPrice: null, tag: 'New', collection: 'bloom-society',
    sizes: ['S', 'M', 'L', 'XL', '2XL'], colors: [{ n: 'Navy', h: '#1b3a6b' }, { n: 'Black', h: '#111' }, { n: 'Cream', h: '#f5f0e1' }], image: PHOTOS[1], featured: false, isNew: true, rating: 4.6, reviews: 89 },
  { id: 3, name: 'Organic Crew Neck', category: 'Organic Cotton', price: 36, oldPrice: null, tag: null, collection: 'earth-tone',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: [{ n: 'Green', h: '#2d6a4f' }, { n: 'White', h: '#fff' }, { n: 'Black', h: '#111' }], image: PHOTOS[2], featured: false, isNew: false, rating: 4.7, reviews: 203 },
  { id: 4, name: 'Abstract Print Tee', category: 'Limited Edition', price: 26, oldPrice: 40, tag: 'Sale', collection: 'street-canvas',
    sizes: ['S', 'M', 'L', 'XL'], colors: [{ n: 'Black', h: '#111' }, { n: 'Red', h: '#e84747' }], image: PHOTOS[3], featured: false, isNew: false, rating: 4.5, reviews: 67 },
  { id: 5, name: 'Heavyweight Box Tee', category: 'Premium Fit', price: 48, oldPrice: null, tag: 'New', collection: 'cyber-punk',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'], colors: [{ n: 'Black', h: '#111' }, { n: 'Gray', h: '#555' }, { n: 'White', h: '#fff' }], image: PHOTOS[4], featured: true, isNew: true, rating: 4.9, reviews: 156 },
  { id: 6, name: 'Wash Garment Dye Tee', category: 'Oversized Fit', price: 44, oldPrice: null, tag: null, collection: 'earth-tone',
    sizes: ['S', 'M', 'L', 'XL'], colors: [{ n: 'Cream', h: '#f5f0e1' }, { n: 'Gray', h: '#555' }], image: PHOTOS[5], featured: false, isNew: false, rating: 4.4, reviews: 42 },
  { id: 7, name: 'Minimal Logo Tee', category: 'Premium Fit', price: 34, oldPrice: null, tag: 'New', collection: 'cyber-punk',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: [{ n: 'White', h: '#fff' }, { n: 'Black', h: '#111' }, { n: 'Navy', h: '#1b3a6b' }], image: PHOTOS[6], featured: false, isNew: true, rating: 4.3, reviews: 78 },
  { id: 8, name: 'Striped Essential Tee', category: 'Organic Cotton', price: 32, oldPrice: null, tag: 'Best seller', collection: 'summer-daze',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'], colors: [{ n: 'Red', h: '#e84747' }, { n: 'Black', h: '#111' }, { n: 'White', h: '#fff' }], image: PHOTOS[7], featured: true, isNew: false, rating: 4.6, reviews: 189 },
  { id: 9, name: 'Drop Shoulder Tee', category: 'Oversized Fit', price: 40, oldPrice: null, tag: null, collection: 'summer-daze',
    sizes: ['S', 'M', 'L', 'XL'], colors: [{ n: 'Gray', h: '#555' }, { n: 'Black', h: '#111' }], image: PHOTOS[8], featured: false, isNew: false, rating: 4.2, reviews: 34 },
  { id: 10, name: 'Solar Flare Tee', category: 'Limited Edition', price: 46, oldPrice: null, tag: 'New', collection: 'summer-daze',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: [{ n: 'Red', h: '#e84747' }, { n: 'Black', h: '#111' }], image: PHOTOS[9], featured: false, isNew: true, rating: 4.7, reviews: 93 },
  { id: 11, name: 'Midnight Run Tee', category: 'Premium Fit', price: 42, oldPrice: null, tag: 'New', collection: 'retro-wave',
    sizes: ['S', 'M', 'L', 'XL', '2XL'], colors: [{ n: 'Navy', h: '#1b3a6b' }, { n: 'Black', h: '#111' }], image: PHOTOS[10], featured: false, isNew: true, rating: 4.5, reviews: 112 },
  { id: 12, name: 'Tropical Haze', category: 'Oversized Fit', price: 38, oldPrice: null, tag: 'New', collection: 'bloom-society',
    sizes: ['XS', 'S', 'M', 'L'], colors: [{ n: 'Green', h: '#2d6a4f' }, { n: 'Red', h: '#e84747' }], image: PHOTOS[0], featured: false, isNew: true, rating: 4.8, reviews: 145 },
  { id: 13, name: 'Geometric Love Tee', category: 'Graphic Tees', price: 36, oldPrice: null, tag: 'New', collection: 'street-canvas',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: [{ n: 'White', h: '#fff' }, { n: 'Black', h: '#111' }], image: PHOTOS[1], featured: false, isNew: true, rating: 4.4, reviews: 56 },
  { id: 14, name: 'Ocean Depth Tee', category: 'Organic Cotton', price: 40, oldPrice: null, tag: 'New', collection: 'earth-tone',
    sizes: ['S', 'M', 'L', 'XL'], colors: [{ n: 'Navy', h: '#1b3a6b' }, { n: 'Cream', h: '#f5f0e1' }], image: PHOTOS[2], featured: false, isNew: true, rating: 4.6, reviews: 88 },
  { id: 15, name: 'Street Code Tee', category: 'Oversized Fit', price: 40, oldPrice: null, tag: 'New', collection: 'street-canvas',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'], colors: [{ n: 'Black', h: '#111' }, { n: 'Gray', h: '#555' }], image: PHOTOS[3], featured: false, isNew: true, rating: 4.3, reviews: 45 },
  { id: 16, name: 'Vintage Logo Tee', category: 'Graphic Tees', price: 18, oldPrice: 30, tag: '-40%', collection: 'retro-wave',
    sizes: ['S', 'M', 'L', 'XL'], colors: [{ n: 'Black', h: '#111' }, { n: 'White', h: '#fff' }], image: PHOTOS[4], featured: false, isNew: false, rating: 4.1, reviews: 234 },
  { id: 17, name: 'Abstract Mind Tee', category: 'Limited Edition', price: 16, oldPrice: 36, tag: '-55%', collection: 'cyber-punk',
    sizes: ['M', 'L', 'XL'], colors: [{ n: 'Gray', h: '#555' }, { n: 'Black', h: '#111' }], image: PHOTOS[5], featured: false, isNew: false, rating: 4.0, reviews: 67 },
  { id: 18, name: 'Mountain Graphic Tee', category: 'Graphic Tees', price: 28, oldPrice: 40, tag: '-30%', collection: 'summer-daze',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: [{ n: 'Black', h: '#111' }, { n: 'White', h: '#fff' }], image: PHOTOS[6], featured: false, isNew: false, rating: 4.5, reviews: 156 },
  { id: 19, name: 'Classic Logo Tee', category: 'Premium Fit', price: 14, oldPrice: 35, tag: '-60%', collection: 'summer-daze',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'], colors: [{ n: 'Black', h: '#111' }, { n: 'White', h: '#fff' }, { n: 'Gray', h: '#555' }], image: PHOTOS[7], featured: false, isNew: false, rating: 4.2, reviews: 312 },
  { id: 20, name: 'Tie Dye Dream Tee', category: 'Oversized Fit', price: 22, oldPrice: 40, tag: '-45%', collection: 'bloom-society',
    sizes: ['S', 'M', 'L', 'XL'], colors: [{ n: 'Red', h: '#e84747' }, { n: 'Gray', h: '#555' }], image: PHOTOS[8], featured: false, isNew: false, rating: 4.6, reviews: 178 },
  { id: 21, name: 'Retro Stripe Tee', category: 'Organic Cotton', price: 20, oldPrice: 40, tag: '-50%', collection: 'retro-wave',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: [{ n: 'Navy', h: '#1b3a6b' }, { n: 'White', h: '#fff' }], image: PHOTOS[9], featured: false, isNew: false, rating: 4.3, reviews: 89 },
  { id: 22, name: 'Linen Blend Tee', category: 'Premium Fit', price: 52, oldPrice: null, tag: null, collection: 'retro-wave',
    sizes: ['XS', 'S', 'M', 'L', 'XL'], colors: [{ n: 'Cream', h: '#f5f0e1' }, { n: 'White', h: '#fff' }, { n: 'Black', h: '#111' }], image: PHOTOS[10], featured: false, isNew: false, rating: 4.7, reviews: 56 },
  { id: 23, name: 'Patchwork Artist Tee', category: 'Limited Edition', price: 54, oldPrice: null, tag: 'New', collection: 'cyber-punk',
    sizes: ['S', 'M', 'L', 'XL'], colors: [{ n: 'Black', h: '#111' }, { n: 'Cream', h: '#f5f0e1' }], image: PHOTOS[0], featured: false, isNew: true, rating: 4.9, reviews: 23 },
  { id: 24, name: 'Eco Logo Tee', category: 'Organic Cotton', price: 28, oldPrice: null, tag: null, collection: 'earth-tone',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'], colors: [{ n: 'Green', h: '#2d6a4f' }, { n: 'White', h: '#fff' }], image: PHOTOS[1], featured: false, isNew: false, rating: 4.4, reviews: 167 },
]
